
import React from 'react';
import ProjectApp from './projects/Medcore/App';
// Auto-generated by AI Architect | Linked at: 1769516000
export default function App() { return (<div className="App"><ProjectApp /></div>); }
